services:
  # Frontend service with hot reloading
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client.dev
    container_name: ecommerce-client-dev
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    ports:
      - "8080:3000"
    depends_on:
      - server
    networks:
      - app-network
    command: npm start

  # Backend service with hot reloading
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server.dev
    container_name: ecommerce-server-dev
    restart: always
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
    command: npm run dev

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: ecommerce-mongo-dev
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=ecommerce
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

# Define networks
networks:
  app-network:
    driver: bridge

# Define volumes
volumes:
  mongo-data:
    driver: local
