FROM node:20-alpine

WORKDIR /app

COPY client/package*.json ./

RUN npm install

# No need to copy source files as they'll be mounted as a volume
# This allows for hot reloading

EXPOSE 3000

CMD ["npm", "start"]