FROM node:20-alpine

WORKDIR /app

COPY server/package*.json ./

RUN npm install

# No need to copy source files as they'll be mounted as a volume
# This allows for hot reloading with nodemon

EXPOSE 3000

CMD ["npm", "run", "dev"]